### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by woakes070048** [stelace/stelace#2]
Does this have stripe already intergrated?

**Comment by woyuen** [comment]
Hi @woakes070048 
Stripe isn't integrated yet, but we have Mangopay as payment service provider.
If you plan to work on this integration, please feel free to contribute ;)

**Comment by abruere** [comment]
Stripe Connect integration is now functional.

Error messages refactoring with Mangopay and some translations in checkout views are still needed and should be completed in the upcoming week. We will close this issue only then.

Stripe / Mangopay KYC integration will follow in the payments roadmap.
