### ISSUE TITLE
Plugin installation fails on MacOs

### ISSUE THREAD

**Issue by izziaraffaele** [stelace/stelace#270]
I've got issues running the command `yarn plugins`. It looks like the problem is with this [line](https://github.com/stelace/stelace/blob/dev/scripts/prepareInstalledPlugins.js#L20) as the `sed` command for MacOs terminal is slightly different.

A simple solution could be the one proposed [here](https://stackoverflow.com/a/57766728/1820242) using the variable `process.platform` to detect the OS running the application

**Comment by abruere** [comment]
Thanks for the issue !

Have you tried using Docker as recommended [there in the readme](https://github.com/stelace/stelace#develop-with-api-server-container)?

Anyway I’ll try to fix this command to enable cross-platform plugins without Docker but I can’t give a deadline yet. I see that I left a comment about shellJS in the file, which could be better than platform-specific commands to maintain.
