### ISSUE TITLE
on install, is not pre-filling the database fields

### ISSUE THREAD

**Issue by intoku** [stelace/stelace#3]
The app is not functional after install, the interface is partly (almost not) functional:
<img width="1139" alt="screen shot 2018-03-25 at 10 33 34" src="https://user-images.githubusercontent.com/30029039/37873233-3fd5a234-3018-11e8-844d-65a7811f71cd.png">
sails starts without error, seems as the migration data is not populated in the database (e.g. listing types, etc..).

What would be the step to re-populate that migration data?

**Comment by abruere** [comment]
Thanks for feedback. Please see https://github.com/stelace/stelace/issues/1#issuecomment-340472160 for appropriate scripts to run to populate database. They can also serve as a template to create your own categories and listing types in scripts.

Readme has just been updated. Please close the issue if this answers your question.

We are working on a new interface for admin to edit listingCategories and listingTypes.

**Comment by intoku** [comment]
Perfect, now works - Thank you for the fast reply!
