### ISSUE TITLE
Dashboard not accessible over proxy

### ISSUE THREAD

**Issue by intoku** [stelace/stelace#4]
Hi, Thank you for the great work!

I have issue that took me already long time - and still cannot find the right setting.

im trying to access https://xxx.xxxxxx.com/dashboard

I have nodejs behind nginx. The nginx proxy config is working as i deploy other apps on the same server - i forward as: proxy_pass 8010

in the local.js i tried all the combinations till now:
- mostly i get 502;
- or: [HPM] Error occurred while trying to proxy request /dashboard from xxx.xxxxxx.com to https://xxx.xxxxxx.com (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
- or 400 Bad Request Request Header Or Cookie Too Large
- or sometimes enters endless loop and reloads the page itself when trying to access /dashboard

the settings file
` secret: '678910', // must replace it with random characters (different from `token.authSecret`)
        url: 'https://xxx.xxxxx.com', 

        // CONFIG
        defaultFeatures: {
            GAMIFICATION: false,
            TAGS: false,
            EVENTS: true,
            SOCIAL_LOGIN: false,
            INCOME_REPORT: false,
            LISTING_CATEGORIES: true,
            SMS: false,
            MAP: true,
        },
        defaultConfig: {
            SERVICE_NAME: 'MyStelace',
        },

        // Stelace SaaS or custom dashboard base url
        dashboardUrl: 'http://localhost:8010', 
        stelaceId: '', // used for Stelace SaaS

        superAdmin: false,
    },

    // SERVER
    port: process.env.PORT || 8010,
    environment: process.env.NODE_ENV || 'development', // replace 'development' with 'production' for production environment
    http: { trustProxy: true }, // replace with `trustProxy: true` if the project runs behind a proxy
    hookTimeout: 600000, // 10 minutes
    // basicAuth: '', // ('username:password' in Base64)

`

thank you

**Comment by abruere** [comment]
Hi @intoku, 

Marketplace management from dashboard is a proprietary feature of our [Software-as-a-Service product](https://stelace.com), but we made sure any other “custom dashboard” could connect to Stelace project with our API in the future if developed by community. Sorry if this was unclear in local.js comment. API docs still missing but we’re working on it.

We intend to grant dashboard basic features to open source community in the coming weeks to make open source marketplace administration easier with a graphical interface (enabling to easily edit external services API keys, set map settings or cancel a transaction for instance). Advanced features such as in-context content edition, stats & graphs, or team roles management will remain exclusive to our SaaS offering though.

Hope this helps and thanks for the issue! Not closing for now until we make this context more understandable in code base.

**Comment by intoku** [comment]
Aaaah, okiee :) Thank you for clarifying! Would be good to copy-paste your answer in the README.md, as i'm sure that saves time to many that go in "trial and error" before realising the exact setup :)

Keep up the great work, thanx!
