### ISSUE TITLE
Warm Greetings

### ISSUE THREAD

**Issue by xposebali** [stelace/stelace#429]
Hi Andy..
Could we join to make some project according to stelace?
please contact me at xposebali@gmail.com, couse I don't know how to contact you.
thanks..

Regards,
Afif

**Comment by abruere** [comment]
Hi Afif, please use this Stelace [contact form (link)](https://stelace.com/contact/) if you want to discuss projects :)

**Comment by xposebali** [comment]
I've been sending message by your website contact link provided but nothing
replied. so I decided to send message from git.
thanks..

**Comment by abruere** [comment]
Oh, yes indeed, thanks ! We’re quite busy these days, but a member of our team will reply soon :)

**Comment by xposebali** [comment]
ok, its not so urgent but the point is I want to request marketplace with
complete features for travel agent and affiliate ticket airplane, tours and
hotel base on your stelace. give me explaining, time for develpment and
price.
thanks..

Regards,
Afif
