### ISSUE TITLE
 Error: connect ECONNREFUSED 127.0.0.1:6543     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#469]
Hello, I'm trying to install Stelace on CentOS Linux release 7.8.2003 (Core), I get an error 
Error: connect ECONNREFUSED 127.0.0.1:6543     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Tell me what could be wrong? Attached an .env file and a screenshot of the error. I hope you can help me.

OC - CentOS Linux release 7.8.2003 (Core),
Node.js - v12.16.3
File.env - [env.zip](https://github.com/stelace/stelace/files/5486569/env.zip) 

EDIT: I am running Stelace on the server http://194.28.84.131:4100 - what do I need to change in order to use it on my server?
![Снимок экрана (268)](https://user-images.githubusercontent.com/23060142/98089457-7066ba00-1e8b-11eb-8a29-c9dcbb389144.png)

**Comment by tereshchuk** [comment]
@abruere I need help 😌😌

**Comment by abruere** [comment]
It seems you missed this line in the [README](https://github.com/stelace/stelace#develop-with-api-server-container):

> You just have to change host from **127.0.0.1 to elasticsearch, postgresql and redis** in your .env file when using containerized API and databases

You also need to set `POSTGRES_PORT=5432` as mentioned in the .env file:

https://github.com/stelace/stelace/blob/11e58c2b30c0b1bda6fc7a9499191c07387a4a03/.env.example#L47-L49

---

And before running knex or starting the server, you can ensure the databases are available if you have any further issue, using:

https://github.com/stelace/stelace/blob/11e58c2b30c0b1bda6fc7a9499191c07387a4a03/.circleci/config.yml#L184-L189

**Comment by tereshchuk** [comment]
> It seems you missed this line in the [README](https://github.com/stelace/stelace#develop-with-api-server-container):
> 
> > You just have to change host from **127.0.0.1 to elasticsearch, postgresql and redis** in your .env file when using containerized API and databases
> 
> You also need to set `POSTGRES_PORT=5432` as mentioned in the .env file:
> 
> https://github.com/stelace/stelace/blob/11e58c2b30c0b1bda6fc7a9499191c07387a4a03/.env.example#L47-L49
> 
> And before running knex or starting the server, you can ensure the databases are available if you have any further issue, using:
> 
> https://github.com/stelace/stelace/blob/11e58c2b30c0b1bda6fc7a9499191c07387a4a03/.circleci/config.yml#L184-L189

And tell me should I replace POSTGRES_HOST = 127.0.0.1 with REDIS_HOST = 194.28.84.131 if I use my server at http://194.28.84.131/. OR should I leave POSTGRES_HOST = 127.0.0.1 ??
[env.zip](https://github.com/stelace/stelace/files/5493541/env.zip) - File env
![Снимок экрана (269)](https://user-images.githubusercontent.com/23060142/98227790-6498f780-1f60-11eb-9bbf-4b7674484619.png)

**Comment by tereshchuk** [comment]
> It seems you missed this line in the [README](https://github.com/stelace/stelace#develop-with-api-server-container):
> 
> > You just have to change host from **127.0.0.1 to elasticsearch, postgresql and redis** in your .env file when using containerized API and databases
> 
> You also need to set `POSTGRES_PORT=5432` as mentioned in the .env file:
> 
> https://github.com/stelace/stelace/blob/11e58c2b30c0b1bda6fc7a9499191c07387a4a03/.env.example#L47-L49
> 
> And before running knex or starting the server, you can ensure the databases are available if you have any further issue, using:
> 
> https://github.com/stelace/stelace/blob/11e58c2b30c0b1bda6fc7a9499191c07387a4a03/.circleci/config.yml#L184-L189

![image](https://user-images.githubusercontent.com/23060142/98227420-fbb17f80-1f5f-11eb-8cf0-902e326c3731.png)

**Comment by tereshchuk** [comment]
@abruere are you here ?

**Comment by abruere** [comment]
Quotes are missing in your screenshot:

```sh
docker-compose -f docker-compose.prod.yml -f docker-compose.override.yml run api /bin/sh -c \ 
'until … do'
```
but databases seem to be running and this was just for convenience and making sure you’re waiting long enough before starting the server or using knex.

> And tell me should I replace POSTGRES_HOST = 127.0.0.1 with REDIS_HOST = 194.28.84.131 if I use my server at http://194.28.84.131/. OR should I leave POSTGRES_HOST = 127.0.0.1 ??

When using Docker for databases (`yarn docker:db`), you have to use names mentioned in the README and in `.env.example` for all `[DB]_HOST` variables, as opposed to `127.0.0.1` when you are running local databases.

Again:

```
# When using Stelace API server docker container:
# REDIS_HOST=redis
# POSTGRES_HOST=postgresql
# ELASTIC_SEARCH_HOST=elasticsearch
```

You usually have to set custom IP in production only when you’re using real production databases (for instance if you installed a Redis datbase on your IP 194.28.84.XXX, or if you’re using redislabs, AWS RDS, ElasticCloud or anything else for your databases).

**Comment by tereshchuk** [comment]
> Quotes are missing in your screenshot:
> 
> ```shell
> docker-compose -f docker-compose.prod.yml -f docker-compose.override.yml run api /bin/sh -c \ 
> 'until … do'
> ```
> 
> but databases seem to be running and this was just for convenience and making sure you’re waiting long enough before starting the server or using knex.
> 
> > And tell me should I replace POSTGRES_HOST = 127.0.0.1 with REDIS_HOST = 194.28.84.131 if I use my server at http://194.28.84.131/. OR should I leave POSTGRES_HOST = 127.0.0.1 ??
> 
> When using Docker for databases (`yarn docker:db`), you have to use names mentioned in the README and in `.env.example` for all `[DB]_HOST` variables, as opposed to `127.0.0.1` when you are running local databases.
> 
> Again:
> 
> ```
> # When using Stelace API server docker container:
> # REDIS_HOST=redis
> # POSTGRES_HOST=postgresql
> # ELASTIC_SEARCH_HOST=elasticsearch
> ```
> 
> You usually have to set custom IP in production only when you’re using real production databases (for instance if you installed a Redis datbase on your IP 194.28.84.XXX, or if you’re using redislabs, AWS RDS, ElasticCloud or anything else for your databases).


Thanks, I seem to have solved the problem, but a new one appeared, could you help me
https://github.com/stelace/stelace/issues/470
