### ISSUE TITLE
Error 400 "body\" is required

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#470]
I have a question. When adding a new product, I get an error (POST request), although the GET request works. What could it be ?? Maybe you need to connect ssl for POST to work?

![Снимок экрана (272)](https://user-images.githubusercontent.com/23060142/98363873-67671b80-2038-11eb-9e11-0c91fbce357c.png)
![Снимок экрана (273)](https://user-images.githubusercontent.com/23060142/98363879-68984880-2038-11eb-915a-a55266af3c26.png)

ERROR:
{
  "message": "\"body\" is required",
  "statusCode": 400,
  "data": [
    {
      "message": "\"body\" is required",
      "path": [],
      "type": "any.required",
      "context": {
        "label": "value"
      }
    }
  ],
  "_stack": [
    "BadRequestError: \"body\" is required",
    "    at errorTransformer (/usr/src/app/src/versions/validation/index.js:91:15)",
    "    at /usr/src/app/src/versions/validation/index.js:158:9",
    "    at nextTick (/usr/src/app/node_modules/restify/lib/chain.js:167:13)",
    "    at processTicksAndRejections (internal/process/task_queues.js:76:11)"
  ]
}

**Comment by tereshchuk** [comment]
And now such an error has appeared.
**Error:**
`MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.'`

**Comment by abruere** [comment]
`"BadRequestError: "body" is required"` for a reason. Why send a `POST` request without a body?

**Please read the [docs](https://stelace.com/docs)** and use the API reference before opening new issues.

**Comment by tereshchuk** [comment]
> `"BadRequestError: "body" is required"` for a reason. Why send a `POST` request without a body?
> 
> **Please read the [docs](https://stelace.com/docs)** and use the API reference before opening new issues.


Thanks a lot, it worked)
You are an excellent advisor))
