### ISSUE TITLE
Error 500 redis

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#479]
Hello, I have this error. It does not arise immediately, but 2 hours after the creation of the stelace project.

{
  "code": "MISCONF",
  "statusCode": 500,
  "message": "Internal Server Error",
  "_stack": [
    "ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.",
    "    at new Command (/root/timka/stelace/node_modules/redis/lib/command.js:12:22)",
    "    at RedisClient.set (/root/timka/stelace/node_modules/redis/lib/commands.js:46:47)",
    "From previous event:",
    "    at setPlatformEnvData (/root/timka/stelace/src/redis.js:232:18)",
    "    at /root/timka/stelace/server/index.js:605:15",
    "    at nextTick (/root/timka/stelace/node_modules/restify/lib/chain.js:167:13)",
    "    at processTicksAndRejections (internal/process/task_queues.js:79:11)"
  ],
  "_message": "MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error."
}

**Comment by woyuen** [comment]
Hi, please always provide your system and database information, otherwise we don't have enough information to help you.

The error expresses a problem to persist to disk. A possible reason is that your system (probably the VPS you mentioned in another issue) has too few memory, so Redis can't work properly and gets into a read-only state.
