### ISSUE TITLE
Issues with cache

### ISSUE THREAD

**Issue by bfis108137** [stelace/stelace#587]
I think these are related so I am going to send them together.  I really didn't find any information related to cache in the docs.

1.)  When adding a new category, patch will not work the first time.  It will return 404 not found.  Simply running the same request again will work but clearly there is some cache issue.  This could be happening with other api sections as well.

2.) After a db reset 
`yarn docker:db:reset`

I will get the previous list of categories list every other time.  Also apparently some cache issue.  I have tried using postman and powershell and both produce the same result.

I would be interested in helping too but I have only got the system working in linux and my pc windows.

**Comment by bfis108137** [comment]
I found the problem.  I was running the system twice on the network.  I don't know why this caused a problem as all setting are for 127.0.0.1 in each instance.  I would be grateful if you could tell me why.  I want to run it twice on my network.  In other words I was running 2 virtual machines with the system running once on each vm.

**Comment by woyuen** [comment]
Hi @bfis108137, thanks for your feedback.
First of all, I can confirm there is no caching system for those requests (Redis isn't used to cache API results).

Concerning the problem you encountered, I suppose you run 2 virtual machines in order to create some load balancing on your system.
The reason you have incoherent results is probably because your two machines target different databases, so this is a misconfiguration problem.
I suggest you to run a virtual machine and run your second machine with the same database credentials/configuration.

Do not hesitate to share some screenshots to illustrate the situation so we can help you more efficiently.

**Comment by bfis108137** [comment]
It's not for load balancing.  It's because I am developing the backend and there is a frontend developer.  I want it to be separate so I can make changes without affecting them.  I have no established load balancer but it seems the requests are alternating between the two instances.

I am going to send you 2 screenshot one after the other.  You can clearly see that the data is completely different.  The real instance at 192.168.20.59 is actually new and the other instance is the one the front end people are using located at 192.168.20.135.  This is very strange I know.
![AsPowerBar_bdq6OOaJjt](https://user-images.githubusercontent.com/4968999/110095306-728f4580-7da5-11eb-9603-b9cf4687cd8d.png)
![AsPowerBar_pgQjItmx8u](https://user-images.githubusercontent.com/4968999/110095310-7327dc00-7da5-11eb-8511-a38596a8fdbd.png)

**Comment by bfis108137** [comment]
I have found a workaround that is currently working.  I put the dev server behind some virtual nat and I don't get other results from the front end server.  I suspect my router or internal networking on my pc.  To get some more direction I would need to run the other server behind nat but I can't do that until later.  I would close it but I would like to update further.  What do you think?

**Comment by woyuen** [comment]
Thanks for your explanations.

I understand better your situation. I think it's related to the auto-discovery functionality of the API server that tries to reach any API services in the same network.
Please try to specify different values (can be arbitrary values) for the environment variable `COTE_ENV` in your two instances and remove your virtual nat to see if that works.
https://github.com/stelace/stelace/blob/4004b212bed92d8230a693627578bedd9cc96f60/.env.example#L97

**Comment by bfis108137** [comment]
This in fact worked.  Thanks
