### ISSUE TITLE
 Transferring an application to a domain

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#606]
Well thank you. But if I was allowed to develop on an ip address on vps. Then I bought the domain timosh.com.ua - and now I want to transfer the stelace applications to the domain. But the application already has data that cannot be deleted. How can I correctly transfer Stelace applications to the timosh.com.ua domain and what changes need to be made in the application?

**Comment by abruere** [comment]
Sorry but we can't provide support related to issues _not_ related to our codebase.

You'll find many resources online to help with DNS records and reverse proxy you could be using (such as nginx), if you're not familiar with these.
