### ISSUE TITLE
http to https

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#616]
I still haven't solved the problem. I tried running another nodejs application and it worked on my nginx https, but stelace doesn't work for some reason. We contacted the technical support of our hoster, where we rent a server - they say that we need to contact the STELACE developers.

      
     Why is Stelace not working on my nginx?
![Снимок экрана (332)](https://user-images.githubusercontent.com/23060142/112103538-937fd500-8bb2-11eb-998c-62203b6b265b.png)

sorry for the persistence.

My NGINX
```
server {
            listen 80;
            listen 127.0.0.1;
            listen [::]:443 ssl ipv6only=on; # managed by Certbot
            listen 443 ssl; # managed by Certbot
            root /var/www/html;
            server_name timosh.com.ua www.timosh.com.ua;
            ssl_certificate /etc/letsencrypt/live/timosh.com.ua/fullchain.pem; # mana>
            ssl_certificate_key /etc/letsencrypt/live/timosh.com.ua/privkey.pem; # ma>
            include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
            ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
             location / {
                      # First attempt to serve request as file, then
                      # as directory, then fall back to displaying a 404.
                      try_files $uri $uri/ =404;
              }
              location /api {
              proxy_pass http://localhost:4100;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
              }
            }
```

My .env  file:
```
Without change. As in the example.
```

My logs in nginx 
```
2021/03/22 20:27:57 [error] 73771#73771: *1530 recv() failed (104: Connection re set by peer) while reading response header from upstream, client: 194.28.84.131, server: testapp, request: "GET / HTTP/1.1", upstream: "http://194.28.84.131:80/ ", host: "timosh.com.ua"
2021/03/22 20:28:19 [alert] 73771#73771: 768 worker_connections are not enough
2021/03/22 20:28:19 [error] 73771#73771: *2299 recv() failed (104: Connection re set by peer) while reading response header from upstream, client: 194.28.84.131, server: testapp, request: "GET / HTTP/1.1", upstream: "http://194.28.84.131:80/ ", host: "194.28.84.131"
2021/03/22 20:30:23 [alert] 73771#73771: 768 worker_connections are not enough
2021/03/22 20:30:23 [error] 73771#73771: *3071 recv() failed (104: Connection re set by peer) while reading response header from upstream, client: 194.28.84.131, server: testapp, request: "GET / HTTP/1.1", upstream: "http://194.28.84.131:80/ ", host: "vipsale.com.ua"
2021/03/22 20:33:18 [alert] 73771#73771: 768 worker_connections are not enough
2021/03/22 20:33:18 [error] 73771#73771: *3842 recv() failed (104: Connection re set by peer) while reading response header from upstream, client: 194.28.84.131, server: testapp, request: "GET / HTTP/1.1", upstream: "http://194.28.84.131:80/ ", host: "timosh.com.ua"
2021/03/22 20:33:19 [alert] 73771#73771: 768 worker_connections are not enough
2021/03/22 20:33:19 [error] 73771#73771: *4607 recv() failed (104: Connection re set by peer) while reading response header from upstream, client: 194.28.84.131, server: testapp, request: "GET /app HTTP/1.1", upstream: "http://194.28.84.131: 80/app", host: "timosh.com.ua"
2021/03/22 20:33:43 [alert] 73771#73771: 768 worker_connections are not enough
2021/03/22 20:33:43 [error] 73771#73771: *5373 recv() failed (104: Connection re set by peer) while reading response header from upstream, client: 194.28.84.131, server: testapp, request: "GET / HTTP/1.1", upstream: "http://194.28.84.131:80/ ", host: "194.28.84.131"
2021/03/22 20:34:43 [alert] 73771#73771: 768 worker_connections are not enough
2021/03/22 20:34:43 [error] 73771#73771: *6139 recv() failed (104: Connection re set by peer) while reading response header from upstream, client: 194.28.84.131, server: testapp, request: "GET / HTTP/1.1", upstream: "http://194.28.84.131:80/ ", host: "194.28.84.131"
2021/03/22 20:35:26 [error] 74348#74348: *3 directory index of "/var/www/html/" is forbidden, client: 88.155.44.155, server: timosh.com.ua, request: "GET / HTTP /1.1", host: "timosh.com.ua"
2021/03/22 20:35:43 [error] 74348#74348: *5 directory index of "/var/www/html/" is forbidden, client: 194.28.84.86, server: timosh.com.ua, request: "GET / HTTP/ 1.1", host: "194.28.84.131"
2021/03/22 20:37:43 [error] 74348#74348: *7 directory index of "/var/www/html/" is forbidden, client: 194.28.84.86, server: timosh.com.ua, request: "GET / HTTP/ 1.1", host: "194.28.84.131"
2021/03/22 20:39:43 [error] 74348#74348: *11 directory index of "/var/www/html/" is forbidden, client: 194.28.84.86, server: timosh.com.ua, request: "GET / HTTP /1.1", host: "194.28.84.131"
2021/03/22 20:40:50 [error] 74348#74348: *12 directory index of "/var/www/html/" is forbidden, client: 5.255.253.66, server: timosh.com.ua, request: "GET / HTTP /1.1", host: "timosh.com.ua"
2021/03/22 20:41:43 [error] 74348#74348: *16 directory index of "/var/www/html/" is forbidden, client: 194.28.84.86, server: timosh.com.ua, request: "GET / HTTP /1.1", host: "194.28.84.131"
2021/03/22 20:43:43 [error] 74348#74348: *21 directory index of "/var/www/html/" is forbidden, client: 194.28.84.86, server: timosh.com.ua, request: "GET / HTTP /1.1", host: "194.28.84.131"
2021/03/23 13:56:24 [error] 74348#74348: *1910 connect() failed (111: Connection refused) while connecting to upstream, client: 93.183.192.183, server: timosh.com.ua, request: "GET /api HTTP/1.1", upstream: "http://[::1]:4100/api", host: "timosh.com.ua"
2021/03/23 13:57:19 [error] 74348#74348: *1914 directory index of "/var/www/html/" is forbidden, client: 194.28.84.86, server: timosh.com.ua, request: "GET / HTTP/1.1", host: "194.28.84.131"
```

**Comment by justinschuldt** [comment]
Hey @tereshchuk, I'm not a developer of Stelace, but I use Stelace and I subscribe to issues on this repo. In the spirit of community and appreciating the work of the developers that made this repo, maybe I can ease the burden on the developers by helping you.

Are you trying to serve your frontend web-app with Nginx as well?  Your Nginx config seems to be setup for serving static assets. Do you actually have a static web app in `/var/www/html` as you describe in `root /var/www/html;`? It is possible to serve both the frontend and backend with Nginx, but the config is more complicated, which is making it more difficult for you to get working. Unless you need to serve your frontend with Nginx, you should not do it. Simpler is better.

It looks like Stelace is answering your request successfully. The `{"code":"ResourceNotFound","message":"/api does not exist"}` is coming from Stelace. You are requesting a route (`/api`) that Stelace does not have. 

Try this:
```
server {
            listen 80;
            listen 127.0.0.1;
            listen [::]:443 ssl ipv6only=on; # managed by Certbot
            listen 443 ssl; # managed by Certbot
            server_name timosh.com.ua www.timosh.com.ua;
            ssl_certificate /etc/letsencrypt/live/timosh.com.ua/fullchain.pem; # mana>
            ssl_certificate_key /etc/letsencrypt/live/timosh.com.ua/privkey.pem; # ma>
            include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
            ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
            location / {
                proxy_pass http://localhost:4100;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }
}
```

Then make your request to https://timosh.com.ua/. If you get a response like: `{"message":"Welcome to Stelace API. Please have a look at https://stelace.com/docs to see what we can build together."}` then that means Nginx is forwarding your requests successfully.

This is not a problem with Stelace, you just need to learn how to use Nginx. Try Googling for "Nginx for node js". If you need more help, you should find a consultant that you can pay to configure it for you. Good luck.

**Comment by tereshchuk** [comment]
> Hey @tereshchuk, I'm not a developer of Stelace, but I use Stelace and I subscribe to issues on this repo. In the spirit of community and appreciating the work of the developers that made this repo, maybe I can ease the burden on the developers by helping you.
> 
> Are you trying to serve your frontend web-app with Nginx as well? Your Nginx config seems to be setup for serving static assets. Do you actually have a static web app in `/var/www/html` as you describe in `root /var/www/html;`? It is possible to serve both the frontend and backend with Nginx, but the config is more complicated, which is making it more difficult for you to get working. Unless you need to serve your frontend with Nginx, you should not do it. Simpler is better.
> 
> It looks like Stelace is answering your request successfully. The `{"code":"ResourceNotFound","message":"/api does not exist"}` is coming from Stelace. You are requesting a route (`/api`) that Stelace does not have.
> 
> Try this:
> 
> ```
> server {
>             listen 80;
>             listen 127.0.0.1;
>             listen [::]:443 ssl ipv6only=on; # managed by Certbot
>             listen 443 ssl; # managed by Certbot
>             server_name timosh.com.ua www.timosh.com.ua;
>             ssl_certificate /etc/letsencrypt/live/timosh.com.ua/fullchain.pem; # mana>
>             ssl_certificate_key /etc/letsencrypt/live/timosh.com.ua/privkey.pem; # ma>
>             include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>             ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
>             location / {
>                 proxy_pass http://localhost:4100;
>                 proxy_http_version 1.1;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection 'upgrade';
>                 proxy_set_header Host $host;
>                 proxy_cache_bypass $http_upgrade;
>             }
> }
> ```
> 
> Then make your request to https://timosh.com.ua/. If you get a response like: `{"message":"Welcome to Stelace API. Please have a look at https://stelace.com/docs to see what we can build together."}` then that means Nginx is forwarding your requests successfully.
> 
> This is not a problem with Stelace, you just need to learn how to use Nginx. Try Googling for "Nginx for node js". If you need more help, you should find a consultant that you can pay to configure it for you. Good luck.

TTHHHAANKS

**Comment by abruere** [comment]
You’re awesome @justinschuldt, thank you !
