### ISSUE TITLE
Installing ElasticSearch plugins fails

### ISSUE THREAD

**Issue by NSPTFR** [stelace/stelace#646]
on v1.0.0-beta.8, installing elasticsearch plugin returns an error:
ERROR: Service 'elasticsearch' failed to build: The command '/bin/sh -c bin/elasticsearch-plugin install analysis-icu' returned a non-zero code: 1

**Comment by woyuen** [comment]
Hi @Nyllon, thanks for reporting this issue.

There's indeed a build problem with the Elasticsearch image due to `analysis-icu` plugin update, because the version wasn't set.
I'll let you know when that's fixed.

**Comment by woyuen** [comment]
Hi @Nyllon, the image build problem is fixed with this PR : https://github.com/stelace/stelace/pull/649

Have a good day!
