### ISSUE TITLE
after transfer of database not able to filter by select custom attributes

### ISSUE THREAD

**Issue by bfis108137** [stelace/stelace#709]
I save the dump
pg_dump -p 6543 -h localhost -U user stelace-core > dump.pg

I am not able to use pg_restore but psql works so I first create the db from the server
createdb -h localhost -p 6543 -U user stelace-core

Then I run
psql -h localhost -p 6543 -U user -d stelace-core < dump.pg

I then follow the instructions in the file restore-from-dump.md

I configure the platform id

I update the platform data using the GET on the old server.  I simply copy the result and send it as a PUT and I do this for both test and live

I didn't update the version because I don't know where to get it but I don't sense this is the issue

I then run elastic sync and redis sync on both test and live

At this point everything works (as far as I can tell) other than the filters based on "select" custom attributes.  I see the custom attribute in the list and I see it in the asset itself but it acts like it's not there.

**Comment by bfis108137** [comment]
I would like to add that I tried it on two different "select" custom attributes

**Comment by woyuen** [comment]
Hi @bfis108137, thanks for the feedback.

Do you mean the "select" custom attributes search filter nothing or everything?

I also don't think the version is the problem.
By the way, you can retrieve it via the following request:
```sh
GET https://<host:port>/store/platforms/<platformId>/data/<env>/version
# with x-stelace-system-key header
# use PUT verb to apply changes
```

I suspect there is a missing step in the documentation for this data to be restored towards Elasticsearch. If you restore into a new Elasticsearch cluster, you need to initialize it first.

Please delete existing indices that have the following name: `index_asset_<platformId>_<env>...`.
Then you can initialize Elasticsearch that will create the correct mapping:
```sh
POST https://<host:port>/store/platforms/<platformId>/elasticsearch/init
# with x-stelace-system-key and x-stelace-env headers
```

Now you can synchronize the existing assets into Elasticsearch with the section `Synchronizing Elasticsearch`.

Please let know if this process works.

**Comment by bfis108137** [comment]
It returns no results.  

It's interesting what you say.  I will check later but it seems not correct since search works on other filters.  I will check anyways.  

I found a workaround that really shouldn't have worked.  I deleted the select custom attributes since I only had 3.  Now I had tons of assets with these custom attributes so I should have gotten an error but it let me do it.  I added them back manually (using the same names properties) and it worked.  This despite the fact that the attributes appeared on the list of the custom attributes at GET /custom-attributes?page=1&nbResultsPerPage=100&order=desc.

**Comment by bfis108137** [comment]
I did this and it did not work.  I created a test server.  I will leave it up and running for a day in case you want me to try something but then I have to destroy it since it's not free.

**Comment by woyuen** [comment]
Thanks for the tests.

If your machine is still up, I would like you to show us the list of indices related to Stelace API and the mapping of your most used index.
Don't worry if it's down.

I have no new ideas for now, so I will notify you if I have something new.

**Comment by bfis108137** [comment]
I have destroyed but I took a snapshot and I can regenerate it if you want.  I don't understand what you want me to check though.  Is it through the api or elasticsearch?

**Comment by woyuen** [comment]
I should have been more specific. I meant checking with Elasticsearch API.

**Comment by bfis108137** [comment]
I have the index but I fear there is data that is not public.  Is there anyway to give it to you privately?  Sorry but I don't think the project manager would approve of it on github.

**Comment by bfis108137** [comment]
I just noticed that there is a initPlatform and checkPlatform.  CheckPlatform returns OK 3 times.  Now I have another issue that I was going to hold off on until this was solved but perhaps it's related.  I keep losing platform data which I set with a put listed in the migration guide.  In other words I have platform ID: 1 and other settings and all of a sudden they disappear.  In addition it seems my environment is not recognized since my oauth is always forwarding to 127.0.0.1.  I know these are separate issues but I feel like maybe they might have the same source problem

**Comment by woyuen** [comment]
Ok, that shouldn't happen. If the PUT response is correct, it must be correctly saved. Maybe you can GET the platform data just after the update to be sure.

For the context, are you migrating PostgreSQL only, or Elasticsearch and Redis as well?

**Comment by bfis108137** [comment]
I get the platform data and it's there.  I just disappears at some point.

I only migrated postgre.

**Comment by bfis108137** [comment]
I did a fresh install on a new server.  As I am making a lot of requests to transfer by api script, I see also the platform id disappears.  I don't think this ever happened before locally.  I don't think it's due to load because I am not running multiple threads.  Now I have run the same test locally and it doesn't happen.  Could it be the server provider?  I am with Digital Ocean (DO).  There are some variables to note.  When I run the test locally, everything is local.  When I run the test on the server I am accessing the server remotely.  The script is not running on the server.  It's possible that DO installs other software that is causing the problem.

**Comment by bfis108137** [comment]
It seems that the issue with the data being lost is separate.  I transferred the data back to my home since the system keeps having problems.  We had the same issue with select custom attributes but the transfer went smoothly.  I didn't even have to set the platformId.  It just worked.  I ran seed but also on the server I ran seed so there should be no difference.  Since these issues seem to be separate, I am opening another issue.  I will continue to discuss just the original issue of select custom attributes.

**Comment by woyuen** [comment]
If you only migrate PostgreSQL, then you shouldn't encounter issues with Elasticsearch synchronization.
That's weird that the mapping you transmitted in private message isn't correct.

Can you confirm that the custom attribute has the type `select` and not `text`?
If it is really the type `select`, do you remember if you created it with type `text`, removed it and recreated it with the type `select` ?

**Comment by bfis108137** [comment]
I can confirm that it is for sure select.  I can give you my dump too in a PM.  I don't recall removing it and readding.  Ironically that is what fixes the issue but the problem seems to come back but I am not sure on this.

**Comment by woyuen** [comment]
Please give me your dump via PM so I can examine the mapping.
Moreover, can you tell me in which commit you run the server. Is it the last commit of the branch master?

**Comment by bfis108137** [comment]
I updated it each time and it always happened.  One other thing I noticed
is that many of the assets with the select custom-attribute type actually
lost that  custom-attribute which is problematic.  I can post this in the
thread if you like.

Gmail won't let me attach the dump file so I am sending you a dropbox link.

https://www.dropbox.com/s/s3k8dw8o5elipzk/stelace2.tar?dl=1

**Comment by bfis108137** [comment]
By updated each time I mean that I did a pull from the stelace git.

**Comment by woyuen** [comment]
I don't know why but I cannot extract the archive your sent me in PM.
Maybe I run incorrect commands. Please can you check the archived can be extracted?

**Comment by bfis108137** [comment]
The file was created using PostGre Client on Debian.  I am able to restore
my database using the following command but i am not able to actually open
using a standard tar software like 7zip.

pg_restore -U user -h localhost -p 6543 -d stelace-core ~/stelace.tar

**Comment by bfis108137** [comment]
I would like to add to this that just now on a seemingly working instance where I previously had the issue, I did a query and it didn't work.  I had a custom attribute with the value wera.png.  I then did a search with "query" : "wera" and I got only 2 results but there were 157.  When I did the search with the custom attribute exactly with the value it worked and I got 157.  In other words "logo":"wera.png"  If I understand query, it searches all text fields including custom attributes.  Correct?

**Comment by woyuen** [comment]
That's correct. Search with query will match all text custom attributes.

**Comment by bfis108137** [comment]
Finally I found the problem.  You must do a platform init and then elasticsearch sync.

**Comment by venachi** [comment]
> Finally I found the problem. You must do a platform init and then elasticsearch sync.
hi, sorry to re-open this. what do you mean by platform init? Is it about `http://localhost:4100/store/platforms/1/elasticsearch/init` ?
