### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by SingularityLab** [stelace/stelace#720]
Hi

We are building our marketplace with Stelace. Really like it.

I've tried multiple times to contact Sales team through the website but had no response.

Is this project still alive? If not, would you mind to opensource the Admin Dashboard? Or at least sell it.

Please, contact me! Email : tech@singularity.kz or +77771191415 (WhatsApp, Telegram)

**Comment by abruere** [comment]
Hi, stelace is alive :)
I’m happy to see it is useful !

Sorry you didn't get an answer from the sales team.
Our whole team has been quite busy lately.

I'll check with them and make sure you get more details very soon (incl. some dashboard demo).
Please note that we don't sell the admin dashboard without our hosted infrastructure currently.

**Comment by SingularityLab** [comment]
@abruere Thanks for reply! Glad to hear.
Nobody contacted me though

**Comment by izziaraffaele** [comment]
BTW @abruere is there any free plan /demo for the hosted infrastructure + dashboard?

**Comment by abruere** [comment]
@izziaraffaele, sorry for being so late.
We don’t have a free plan anymore, but demos with the sales team are available for Enterprise users.

Stelace software is pretty big and it was not helpful to onboard users without appropriate dev resources.
