### ISSUE TITLE
Stelace instance stops whenever I create a user

### ISSUE THREAD

**Issue by snikpic** [stelace/stelace#733]
Hi,

I am running a local dockerized instance of Stelace on my computer. Everything is properly running (incl. DB, redis and elasticsearch) and I can for example create assets. However, whenever I try to create a user with a username and password, the Stelace instance stops and I don't get any information in the log about the potential root cause.

Here is how I am performing the call through Stelace SDK : 
`  
await stelace.users.create({
        username: 'user@example.com',
        password: 'secretPassword'
 })
`

When looking at the Postgres container, i get this error:
`unexpected eof on client connection with an open transaction`
=> It seems that the stelace instance stops in the middle of the transaction.

I encountered this issue both on the dev and master branch. Any idea on how to solve this ? 

Thanks a ton for your support

**Comment by marsan957** [comment]
same problem here, any solution?

**Comment by marsan957** [comment]
Solution: start api server with "yarn start" and not in container
