### ISSUE TITLE
contato

### ISSUE THREAD

**Issue by marcoscostabistroo** [stelace/stelace#738]
Hello I'm trying to contact the site for a few days and I have some questions:

The output option what is the value?

Can we use a trial license to test the saas option?

I would like to know if it would be possible to carry out exchanges between products, could the system support this purpose?

I would like to know more about plugin creation, I need to make a payment gateway from my country....

please wait for the contact ..

**Comment by abruere** [comment]
Hello,

It seems you’re already in touch with our team via our [contact form](https://stelace.com/contact/), so I’m closing this.

Please note that developers are free to create their own plugin to add to stelace open-source server, such as [stelace-stripe](https://github.com/stelace/stelace) for payments.
