### ISSUE TITLE
Date filter does not work with exact match but only with range

### ISSUE THREAD

**Issue by izziaraffaele** [stelace/stelace#741]
Apparently, date like filters (eg. createdDate, updatedDate) should support exact match `createdDate=2021-10-26` but in reality it works only with range `createdDate[gte]=2021-10-26&createdDate[lte]=2021-10-26`.

I'm using `v1.0.0-beta.8`. I have not tested the dev branch yet. Can you guys confirm this is an issue?

**Comment by izziaraffaele** [comment]
It appears the same issue affects numeric filters. Filtering `/assets` by quantity with an exact match (`quantity=1`) returns all records. Using range like `quantity[gte]=1&quantity[lte]=1` works as expected

**Comment by woyuen** [comment]
Hi @izziaraffaele, thanks for reporting this bug. The exact value filter was indeed broken.
The bug fix is available in the `dev` branch.

**Comment by izziaraffaele** [comment]
Amazing! Thanks!
