### ISSUE TITLE
search for items with quantity of 0

### ISSUE THREAD

**Issue by bfis108137** [stelace/stelace#743]
The search option only allows for searches of assets with a quantity of 0 or more.  I am well aware of the fact that officially it returns only assets with a quantity of 1 or more but there are cases where a search is desired on assets with a quantity of 0.  For example, a user wants to know all the assets with a quantity of 0 but he wants to filter his query by a custom attribute.

Since stelace is exhibiting expected behavior, this is a feature request.

**Comment by bfis108137** [comment]
I am closing this.  Somehow I missed that you just need to use the availabilityFilter.  So for anyone else, you would do something like this.

```
{
    "customAttributes": {
        "someAttribute": true
    }
    "availabilityFilter": {
        "enabled": false
    }
}
```

**Comment by abruere** [comment]
Thanks for sharing !
Indeed availability filter excludes assets without any quantity available.
It could to be more explicit in the docs.
