### ISSUE TITLE
Create review throws an unexpected error when it's not connected to neither an asset nor a transaction

### ISSUE THREAD

**Issue by izziaraffaele** [stelace/stelace#745]
I was trying to create a review for a user specifying only the score parameter but I'm getting a 500 error. I think the problem is with [this line](https://github.com/stelace/stelace/blob/dev/plugins/rating/services/rating.js#L313) which throws an error when the transaction object is empty.

To replicate you can just try a review that looks like this
`{
    "authorId": "usr_ZEyVd3e14m61n0QnR4m6",
    "targetId": "usr_yTyZSfe14zF1n0eIm4zF",
    "score": 10
}`

**Comment by woyuen** [comment]
Sorry for my late answer and thanks for spotting this issue.
I fixed it with this commit : https://github.com/stelace/stelace/commit/3705d1068aeceb6faeb6f447d29329147d9884cd
