### ISSUE TITLE
error on password reset

### ISSUE THREAD

**Issue by bfis108137** [stelace/stelace#746]
I get the following error when running a password reset on the dev branch.  Our db was created on the master branch however we are sending the header x-stelace-version: 2019-02-20

"DBError: insert into \"s1_live\".\"event\" (\"apiVersion\", \"changesRequested\", \"createdDate\", \"createdTimestamp\", \"emitter\", \"emitterId\", \"id\", \"metadata\", \"object\", \"objectId\", \"objectType\", \"parentId\", \"relatedObjectsIds\", \"type\") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning \"id\" - column \"createdTimestamp\" of relation \"event\" does not exist",
        "    at Object.wrapError (/var/www/services/stelace/node_modules/db-errors/lib/dbErrors.js:19:14)",
        "    at SchemaQueryBuilder.<anonymous> (/var/www/services/stelace/node_modules/objection-db-errors/index.js:9:40)",
        "    at OnErrorOperation.onError (/var/www/services/stelace/node_modules/objection/lib/queryBuilder/operations/OnErrorOperation.js:17:22)",
        "    at /var/www/services/stelace/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:358:37",
        "    at Object.promiseTry [as try] (/var/www/services/stelace/node_modules/objection/lib/utils/promiseUtils/try.js:8:26)",
        "    at SchemaQueryBuilder.callAsyncOperationMethod (/var/www/services/stelace/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:358:11)",
        "    at /var/www/services/stelace/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1299:17",
        "From previous event:",
        "    at processImmediate (internal/timers.js:464:21)",
        "From previous event:",
        "    at SchemaQueryBuilder.execute (/var/www/services/stelace/node_modules/objection/lib/queryBuilder/QueryBuilder.js:581:13)",
        "    at SchemaQueryBuilder.then (/var/www/services/stelace/node_modules/objection/lib/queryBuilder/QueryBuilder.js:496:26)"

**Comment by woyuen** [comment]
Sorry for my late answer.

The dev branch uses a new database named TimescaleDB which is an extension of PostgreSQL but adds some more features and optimization, like time series and storage compression : https://github.com/stelace/stelace/pull/349

Your database created in master branch won't work with the dev branch application code.
We didn't have dedicated resources to align dev and master branches for now, so I suggest to fallback to master branch.

**Comment by bfis108137** [comment]
> Sorry for my late answer.
> 
> The dev branch uses a new database named TimescaleDB which is an extension of PostgreSQL but adds some more features and optimization, like time series and storage compression : #349
> 
> Your database created in master branch won't work with the dev branch application code. We didn't have dedicated resources to align dev and master branches for now, so I suggest to fallback to master branch.

I will tell you what we did in the end and it's working but I don't know if I recommend this.  We really needed some of the features in the dev branch.  We did a fresh install and then we ran a restore on the new db from the old db but without deleting the new db.  Basically just a restore which will give you all kinds of errors on duplicate keys and relations but in the end it works for us.  It has been so long that I really can't remember exactly how we did it but the system is running smoothly afaik.  I would however recommend that there be some orderly method for doing this operation.

**Comment by woyuen** [comment]
Thanks for the explanation.

I think your method can work. Another solution is to run `migrateTimescaleDB.js` script by following this migration document : https://github.com/stelace/stelace/blob/dev/docs/migration-to-timescaledb.md

**Comment by woyuen** [comment]
I'm closing this issue but don't hesitate to post additional messages if needed.
