### ISSUE TITLE
Server hangs after being killed and only computer reboot helps

### ISSUE THREAD

**Issue by bintoll** [stelace/stelace#749]
Hello everyone! 
First of all I would like to tell that most likely I am doing something wrong, as I try to use the stelace for the first time in an ongoing project, but I kindly ask to point it out if you know.

I am using Mac OS m1. And what I experience now so far is: after 2 or more tries of shutting down by CRL+C or sending a signal to shut down node process after `yarn start` my computer starts to work slow, terminal freezes, vsCode freezes, and even browser stops loading pages. And after some minutes computer shuts down. Only reboot helps. And that happens not just on first time but on second-forth.
I tried to use debug mode and I saw that server scans for free ports. For first times it works, but then it looks like that server was not able to find ports or something like this BUT no more logs after that, command line hangs. And after that sending a kill signal to node does not kill it at all. Once after this I saw debug logs with countless amount of such logs:
`{"context":{"application":"stelace-core","logLevel":50,"err":{"errno":-57,"code":"ENOTCONN","syscall":"recvmsg","name":"Error","message":"recvmsg ENOTCONN","stack":"Error: recvmsg ENOTCONN\n    at UDP.onMessage [as onmessage] (dgram.js:931:31)"}},"message":"Uncaught exception","sequence":20475,"time":1643483059537,"version»:»1.0.0»}
` 
But I saw it just once. Looks like the spam of this logs causes that heavy issue. Tried to research it, but without any result.

**Comment by bintoll** [comment]
After disabling Mac OS firewall everything starts working as expected. 

I am not 100% sure, but my assumption is that after few tries of scanning port Mac OS firewall do not allow to use this port for this process. And script that is is trying to find a free port goes into infinite loop, this causes whole computer to freeze. There should be some limit for this script that tries to find free port. 

UPD: Not closing the issue, I think that it is still not solved even though the problem has been overcome.

**Comment by woyuen** [comment]
Thanks for the issue investigation.

We didn't encounter this freezing issue with Linux so your feedback is precious.
The port scanning is performed by the library [cote](https://github.com/dashersw/cote).
We'll evaluate if something can be done to improve this situation.
